# Generated by Django 2.2.12 on 2020-05-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('fname', models.CharField(max_length=40)),
            ],
        ),
    ]
