# Generated by Django 2.2.12 on 2020-05-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_c', models.CharField(max_length=300)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Professeur')),
            ],
        ),
    ]
