# Generated by Django 2.2.12 on 2020-05-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_cour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_username', models.CharField(max_length=40)),
                ('E_email', models.EmailField(max_length=120)),
                ('E_password', models.CharField(max_length=40)),
                ('E_lname', models.CharField(max_length=40)),
                ('E_fname', models.CharField(max_length=40)),
                ('E_filiere', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Cour',
        ),
    ]
