# Generated by Django 2.2.12 on 2020-05-11 06:29

from django.db import migrations, models
import myApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20200511_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_C', models.CharField(max_length=300)),
                ('Element_C', models.CharField(max_length=50)),
                ('Filiere_C', models.CharField(max_length=100)),
                ('Module_C', models.CharField(max_length=200)),
                ('Semestre', models.IntegerField()),
                ('PDF_C', models.FileField(null=True, upload_to=myApp.models.upload_PDF_path)),
                ('Video_C', models.FileField(null=True, upload_to=myApp.models.upload_video_path)),
            ],
        ),
    ]
