# Generated by Django 2.2.12 on 2020-05-13 22:28

from django.db import migrations, models
import myApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_cour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='PDF_C',
            field=models.FileField(blank=True, null=True, upload_to=myApp.models.upload_PDF_path),
        ),
        migrations.AlterField(
            model_name='cour',
            name='Video_C',
            field=models.FileField(blank=True, null=True, upload_to=myApp.models.upload_video_path),
        ),
    ]
