# Generated by Django 2.2.12 on 2020-05-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_cour_prof_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='Prof_C',
            field=models.CharField(max_length=100),
        ),
    ]
